name: C/C++ CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt update
      run: sudo apt-get update 
    - name: Install tools and libs
      run: sudo apt-get install build-essential git cmake firebird-dev libwxgtk*-gtk3-dev -y
    - name: CMake
      run: |
          mkdir build
          cd build
          cmake ..
    - name: Build
      run: make
      working-directory: ./build

